name: Deploy to GitHub Pages

on:
  # Despliega cuando hagas push a la rama "main" (o la que uses).
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear (checkout) el código
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Instalar Node.js (versión 18)
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Configurar las variables de entorno (Secrets)
      - name: Set vite api key
        run: echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> $GITHUB_ENV

      - name: Set open ai api key
        run: echo "VITE_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Set firebase auth domain
        run: echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV

      - name: Set firebase project id
        run: echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Set firebase storage bucket
        run: echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV

      - name: Set firebase messaging sender id
        run: echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV

      - name: Set firebase app id
        run: echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> $GITHUB_ENV

      # 5. Compilar (build) la aplicación
      - name: Build
        run: npm run build

      # 6. Cargar los artefactos del build (la carpeta dist)
      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  # Una vez subidos los archivos, se despliegan a GitHub Pages
  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
