name: Deploy to GitHub Pages

on:
  # Despliega cuando hagas push a la rama "main" (o la que uses).
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear (checkout) el código
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Instalar Node.js (versión 18)
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Configurar las variables de entorno (Secrets)
      - name: Set environment variables
        run: |
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> $GITHUB_ENV

      # 5. Compilar (build) la aplicación
      - name: Build
        run: npm run build

      # 6. Crear una carpeta temporal sin archivos sensibles
      - name: Prepare deployment folder
        run: |
          mkdir deployment
          cp -R dist/* deployment/
          # Excluir archivos sensibles
          find deployment -name "*.env" -delete
          find deployment -name "*.key" -delete
          find deployment -name "*.json" -delete

      # 7. Subir los artefactos del build (asegurando el nombre correcto)
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: github-pages # Nombre esperado por deploy-pages
          path: ./deployment
          overwrite: true

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
